log-level: info

ipsc:
  interface: "ipsc0"
  port: 50000
  ip: "10.10.250.1"
  subnet-mask: 24
  auth:
    enabled: false
    key: ""

hbrp:
  master-server: "3104.master.brandmeister.network:62030"
  password: "passw0rd"

  callsign: KI5VMF
  radio-id: 319186803

  # Frequency in Hz:
  rx-freq: 429075000
  tx-freq: 424075000

  color-code: 7
  # Optional latitude and longitude:
  # latitude: 30.000000
  # longitude: -97.000000

  # Height in meters:
  height: 3

  # Optional location:
  location: "Moore, OK"

  # Optional description:
  # description: ""

  # Optional URL:
  # url: ""
